# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

schedules:
- cron: "10 * * * *"
  displayName: Hourly build
  branches:
    include:
    - master
  always: true

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: curl -so /dev/null -w "%{http_code}" https://hiteam-oneindex.azurewebsites.net/ || true
  displayName: 'Access the website'

- script: |
    curl -so /dev/null -w "%{http_code}" -u $VSTS_AUTH https://dev.azure.com/peterjc123 || true
  displayName: 'Keep pipeline running'
  env:
    VSTS_AUTH: $(token)